#!/bin/bash
set -e
urls=(
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/P1_cosmofile.mat?versionId=xLh.bl5ZXWfaMDvlmxUJJVdwHsmAu.gl data/things_meg/raw_meg/P1_cosmofile.mat"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/P2_cosmofile.mat?versionId=Eb_vOWRUeoOSGVHnzju98t8Nh8m.O2Fv data/things_meg/raw_meg/P2_cosmofile.mat"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/P3_cosmofile.mat?versionId=xM3WYmNG306sUavOwRa7TXrwEeq.7iSk data/things_meg/raw_meg/P3_cosmofile.mat"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/P4_cosmofile.mat?versionId=sxQz_cnqxk5itTZ51mklGVgpaQyx_Fll data/things_meg/raw_meg/P4_cosmofile.mat"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S1.csv?versionId=0briZh0Uqh_NBs1wUB2XPhF_Cxreaqq5 data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S1.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S10.csv?versionId=VQ0GaNLE.4FiYLvu7_Mdh_0jqqbJmSFr data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S10.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S11.csv?versionId=XS53TP0uqZlaaYitPRSjOS.MikvQ_eTH data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S11.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S12.csv?versionId=J09NAg2eXSthePuiB_4hePxYjmOdctLM data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S12.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S2.csv?versionId=f6VPWAE0q7KKcEg9ti3QeUq7phFo0BiI data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S2.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S3.csv?versionId=mehqT3TvmQF2oFCKy.WSviSPHBF8xhL4 data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S3.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S4.csv?versionId=1m3PYeepU6DMMkbG7HrXxRd_fO.UZ_9B data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S4.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S5.csv?versionId=coFCMxwu1EtyESkOk98EyIclQNyocs4L data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S5.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S6.csv?versionId=xkhZWZ8c1gqXD9ofIuaFUHnpxF36.ljo data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S6.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S7.csv?versionId=VHNfTNDeI2MGa_D5VAobIVa4C2Bap0we data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S7.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S8.csv?versionId=rZ1qvv1K44X2BFbKHQ9qk8D1xVK8Rpi8 data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S8.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P1_S9.csv?versionId=MPND4xzCjAMNuZCHO_6AEmySpEtRtcqE data/things_meg/raw_meg/eyes_epoched_cleaned_P1_S9.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S1.csv?versionId=Wwr3mWpLLpnweHSFOYRJDAg8Cia8WPbT data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S1.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S10.csv?versionId=W5wH.ebDTfzRBdPiAdhztySa9QdKh8bI data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S10.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S11.csv?versionId=SgtxINjs_O7ansuzJCFuSIcQ9TSwWS0l data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S11.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S12.csv?versionId=Q.jG7b4qjU7kbGzzWj5EHMw6cp02rwpX data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S12.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S2.csv?versionId=KArG05zd_zxmCpgrnYX5X8ehlZU6eVtj data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S2.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S3.csv?versionId=0aQonxCTjNw31UHUMGCPDSWxWqrjCjzT data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S3.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S4.csv?versionId=HXf3MqbAQkJsD52CCVz0dRLwndzkDLhO data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S4.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S5.csv?versionId=vStauUtvL1lF1XPpwCSlf0TamlHJVTy9 data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S5.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S6.csv?versionId=trEC5cezK3Vgb2k5ok4iuJ6hGsJbx9mu data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S6.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S7.csv?versionId=IAEJooQenhS7FCy3RAjPhVjcyNZe09Am data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S7.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S8.csv?versionId=hsKxHzo38SNjHQlACKMkoALpQG8.8usA data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S8.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P2_S9.csv?versionId=ct_9UbI1_cD9FbQJjxevb70_KyaG9sY6 data/things_meg/raw_meg/eyes_epoched_cleaned_P2_S9.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S1.csv?versionId=CJ1zKl0dgElNJ1G5UFnJ4XYCHSEUbjNu data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S1.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S10.csv?versionId=hHClozkMW2SgR7DHFbGxUrsMUvO4cyNA data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S10.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S11.csv?versionId=p5uJw1e6Auzy4cFwegal1nLWRQ4RcHoZ data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S11.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S12.csv?versionId=26tfJuqUrEujJMDKq.0dildXlV36iNYp data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S12.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S2.csv?versionId=.wnPDFrpmTzP9DeWUVcvUWrRdSQcvjg0 data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S2.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S3.csv?versionId=DneLbu6t3uT4wsMbp23KYorXC30U80iS data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S3.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S4.csv?versionId=i47VS7ypicJR2sWgoA830qakvWWQAkvn data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S4.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S5.csv?versionId=zB7GAHqYCJxCDtsqId4g5t9WShd_XCeK data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S5.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S6.csv?versionId=AtynfUV4az3ZmDjiCk_Cdw5IxI6ys52m data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S6.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S7.csv?versionId=sp6gWVEyMbIx2aZsPw9moGk7tnquO2CC data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S7.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S8.csv?versionId=0_R6SCroL75xxOuXrCg5SrskraA5uzs4 data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S8.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P3_S9.csv?versionId=XkgohmUw3IjM9I9A1TgsfB3.60SSWJ0o data/things_meg/raw_meg/eyes_epoched_cleaned_P3_S9.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S1.csv?versionId=XX1CLeAcQORlF5tuzqyVtUKg3W0v9wIL data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S1.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S10.csv?versionId=XviX2Nw0zhaWFSr32tIO_HOtMUajoK6q data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S10.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S11.csv?versionId=KAASNZP3qO9ahszecrSz60i3Wi0_YZeG data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S11.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S12.csv?versionId=EVjCntdy2aaqJyDUbAMwt4BeVE8yJcxq data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S12.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S2.csv?versionId=cjfKRFN6hbqhXw5PHWOyWj_PGxRIHoiD data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S2.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S3.csv?versionId=1_rq5_JLrfF3EdqH.rtUd7H2K6KEP7rF data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S3.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S4.csv?versionId=qEYSoy45s.O6rrBi0yPoweyfDL0JIFaC data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S4.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S5.csv?versionId=8ugek3azxIfjlQgczUeNsjMEpkiIoWZy data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S5.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S6.csv?versionId=eeKupr3mBPKRGK18Q2ilefA3r2iA2mwQ data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S6.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S7.csv?versionId=CHJ.tIhyIzsB9ndUEnjnI1JU8clmpj8N data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S7.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S8.csv?versionId=TU0prfu8ImHKojibim3p37nbtbJ1D0mj data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S8.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/eyes_epoched_cleaned_P4_S9.csv?versionId=4BBaCw6Vs0WXgbk5HxOL1ZEPH2KfBLdN data/things_meg/raw_meg/eyes_epoched_cleaned_P4_S9.csv"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P1-epo-1.fif?versionId=VEFpBYggusLPxNIKlN21eEtrjpo4DcBP data/things_meg/raw_meg/preprocessed_P1-epo-1.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P1-epo-2.fif?versionId=hVx8E4e0xIymnQ3nHKFnNAhQHsr7jKlQ data/things_meg/raw_meg/preprocessed_P1-epo-2.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P1-epo-3.fif?versionId=1jVDhw2KOJz7b_6ApO2a9J4vy_8jqqhn data/things_meg/raw_meg/preprocessed_P1-epo-3.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P1-epo.fif?versionId=_KO81vnVItjzcxrR91AFeHh8sA7YiuB9 data/things_meg/raw_meg/preprocessed_P1-epo.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P2-epo-1.fif?versionId=yIZzH6fajlVFCen182u0nGLl5sbWKs0w data/things_meg/raw_meg/preprocessed_P2-epo-1.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P2-epo-2.fif?versionId=qQ9bWzptOpO8CZlBhT4c5erDOA5Do67a data/things_meg/raw_meg/preprocessed_P2-epo-2.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P2-epo-3.fif?versionId=uRES5t7k47rQTCDUNlFN5_rRmjNOemtW data/things_meg/raw_meg/preprocessed_P2-epo-3.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P2-epo.fif?versionId=yYjGg9sMwgC3FozM8Sc_HXmKoSd_6Qnv data/things_meg/raw_meg/preprocessed_P2-epo.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P3-epo-1.fif?versionId=JYdYRMFUzwsz8354Fz9sQQbnQ.Ozstbb data/things_meg/raw_meg/preprocessed_P3-epo-1.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P3-epo-2.fif?versionId=mUABa6OLpBG1Vu0A9IsFpOkgWjMBTuG8 data/things_meg/raw_meg/preprocessed_P3-epo-2.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P3-epo-3.fif?versionId=LadUGeGvC.s2wAqYEMXEzD4_VjD1aRJg data/things_meg/raw_meg/preprocessed_P3-epo-3.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P3-epo.fif?versionId=oaTbATaOOvX.UtsD5gA9ET7RJoZljTsB data/things_meg/raw_meg/preprocessed_P3-epo.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P4-epo-1.fif?versionId=LGG8UJiqW83Z5Mgpiv5LQDgUgs0kYn9y data/things_meg/raw_meg/preprocessed_P4-epo-1.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P4-epo-2.fif?versionId=tdx2wKa7QOpMjBzsN4py4Y.rYhW9vp26 data/things_meg/raw_meg/preprocessed_P4-epo-2.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P4-epo-3.fif?versionId=gajLhEHnXBlMs.EMnyXyFtJ_SVvw_gOT data/things_meg/raw_meg/preprocessed_P4-epo-3.fif"
"https://s3.amazonaws.com/openneuro.org/ds004212/derivatives/preprocessed/preprocessed_P4-epo.fif?versionId=LM9PMqdfCcx8h9qjfU_W69WU0Ol9ECdl data/things_meg/raw_meg/preprocessed_P4-epo.fif"
)

for entry in "${urls[@]}"; do
    read -r url path <<< "$entry"
    echo "Downloading：$path"
    curl -C - --retry 5 --retry-delay 5 --create-dirs -L -o "$path" "$url"
done